version: "3.3"

services:
  dbb:
    build: 
      context: ./db
    container_name: lavagna_db
    environment:
       MYSQL_ROOT_PASSWORD: mypd
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbpass
       MYSQL_DATABASE: lavagna
    restart: on-failure
    volumes:
       - dbb:/var/lib/mysql
    networks:
      - lavagna_backend
   
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      timeout: 20s
      retries: 5
      
       
  app:
    
    build: .
    container_name: lavagna_app
    volumes:
        - ./bin/entrypoint.sh:/app/entrypoint.sh
    
    environment:
       DB_DIALECT: MYSQL
       DB_URL: jdbc:mysql://lavagna_db:3306/lavagna?autoReconnect=true&useSSL=false
       DB_USER: dbuser
       DB_PASS: dbpass
       SPRING_PROFILE: dev
    restart: on-failure
    ports:
      - 8087:8080
    depends_on:
      - dbb
    networks:
      - lavagna_backend
      - lavagna_frontend
    entrypoint: ["/bin/sh","/app/entrypoint.sh"]
    
    
  webb:
    build:
      context: ./nginx_config
    container_name: lavagna_web
    restart: always
    volumes:
        - ./nginx_config/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8082:80
    networks:
      - lavagna_frontend


volumes:
  dbb:
  
  
  

networks:
  lavagna_backend:
  lavagna_frontend:
     
      